name: Pull Requests
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
        check-latest: true
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/golangci-lint
          ~/.cache/go-build
        key: ${{ runner.os }}-go-lint-${{ hashFiles('**/go.sum') }}
    - name: Install Developer Tools
      run: make install-tools
    - name: Execute Linter
      run: make lint
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
        check-latest: true
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/golangci-lint
          ~/.cache/go-build
        key: ${{ runner.os }}-go-lint-${{ hashFiles('**/go.sum') }}
    - name: Execute Build
      run: make build
    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v3
      with:
        path: bin/koko-slack-bot
  unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
        check-latest: true
    - name: Cache Golang Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-unit-${{ hashFiles('**/go.sum') }}
    - name: Execute Tests and Coverage
      run: make test
    - name: Upload Code Coverage Results
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage/
